### ISSUE TITLE
Add multiplication for the dice rolls

### ISSUE THREAD

**Issue by BlackLiger** [DavidWylie/RollWitch#8]
**Is your feature request related to a problem? Please describe.**
Multiplication of the results of dicerolls is sometimes needed for character generation, for example in Stormbringer 4th edition.

**Describe the solution you'd like**
Allow the bot to handle requests to do, for example, !r 3d6*100
It would also be useful if it could handle brackets in a calculation, but that isn't vital.

**Describe alternatives you've considered**
I cannot think of anything that would be an alternative for this except manually handling the multiplication.

**Comment by DavidWylie** [comment]
Multiplaction and Division are now supported.
